[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_program = "8S7KF153nyYtXSsVNokzZQdpDz3StcfiPBtmt73ZtBJy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sadeq/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
